[project]
name = "cnn"
version = "0.1.0"
requires-python = ">=3.10, <=3.13"
dependencies = [
    "flask>=3.1.2",
    "jax>=0.6.2",
    "matplotlib>=3.10.8",
    "opencv-python>=4.13.0.90",
    "scipy>=1.15.3",
    "tensorflow>=2.20.0",
    "torch>=2.10.0",
]
